#!/usr/bin/env sh

function printUsage()
{
	echo "Usage: $0 objFile"
	echo "  Patch obj file generated by Blender to fit my need"
}

if [ "$1" == '' ]
then
	printUsage
	exit 1
fi

if [ ! -f $1 ]
then
	echo 'file not fount'
	exit 1
fi

awk '{gsub(/\/\//, "/0/"); print $0}' $1
